[package]
name = "chromebook-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
async-fs = "2.0.0"
async-process = "2.0.0"
cp_r = "0.5.1"
fs_extra = "1.3.0"
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"] }
walkdir = "2.4.0"
